{% set version = "7.0.10-21" %}

package:
  name: imagemagick
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/ImageMagick/ImageMagick/archive/{{ version }}.tar.gz
  sha256: 98afa3ca26db3115e83a5d03895789110cd2e19f09fd86af1b692c51cd3d5153

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - bzip2
    - fftw
    - fontconfig
    - fonts-conda-forge
    - freetype
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - jpeg
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl
    - pkg-config
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib
  run:
    - bzip2
    - fftw
    - fontconfig
    - freetype
    - fonts-conda-forge
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - jpeg
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl
    - pkg-config
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib

test:
  commands:
    - convert -version
    - Magick++-config --cflags
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.imagemagick.org/
  license: ImageMagick
  license_file: LICENSE
  summary: Software suite to create, edit, compose, or convert bitmap images.

extra:
  recipe-maintainers:
    - ocefpaf
    - halldc
