{% set version = "7.1.1-9" %}

package:
  name: imagemagick
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/ImageMagick/ImageMagick/archive/{{ version }}.tar.gz
  sha256: 096aff6708bf5e45a7c949fbdf7fb6fd54f09d0ef9e42121a51bf2b6a92a131e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - make  # [linux]
    - bzip2
    - fftw
    - fontconfig
    - fonts-conda-forge
    - freetype
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - libjpeg-turbo
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl *
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib
    - glib
  run:
    - bzip2
    - fftw
    - fontconfig
    - freetype
    - fonts-conda-forge
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl *
    - pkg-config
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib

test:
  commands:
    - convert -version
    - Magick++-config --cflags

about:
  home: http://www.imagemagick.org/
  license: ImageMagick
  license_file: LICENSE
  summary: Software suite to create, edit, compose, or convert bitmap images.

extra:
  recipe-maintainers:
    - ocefpaf
    - halldc
